            <footer class="footer text-right"<?php if($vista == 'Sala de espera'): ?> style="left: 0;" <?php endif; ?>>
                <span class="pull-left"><strong>Pech</strong> <small>v21.08.0 <small>beta</small></small></span>
                © <?= date('Y') ?> <small>Hospital Veterinario</small> Peek
            </footer>
    </div>

    <script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>

    <script>
        $(function(){});
    </script>
