<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" type="image/png" sizes="16x16" href="<?=URL_ROOT?>/assets/images/favicon.ico">
		<title><?= SITE_NAME ?></title>
		<link href="<?= URL_ROOT ?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?= URL_ROOT ?>/assets/css/style.css" rel="stylesheet">
		<link href="<?= URL_ROOT ?>/assets/css/colors/blue.css" id="theme" rel="stylesheet">
		<link href="<?= URL_ROOT ?>/assets/plugins/toast/toastr.min.css" rel="stylesheet" />
		<style>
			.footer { left: 0; background-color: transparent; }
		</style>
	</head>
	<body>
		<div class="preloader">
			<svg class="circular" viewBox="25 25 50 50">
				<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
		</div>
		<section id="wrapper">
			<div class="login-register">
				<div class="login-box card">
					<div class="card-body">
						<h1 class="box-title m-b-20 text-center">Ingresar</h1>
						<div class="form-group ">
							<div class="col-xs-12 text-center">
								<h3>Ingresa tu <b>Switch Code</b></h3>
							</div>
							<div class="col-xs-12">
								<input class="form-control form-control-lg text-center" type="password" required="" placeholder="SwitchCode" maxlength="4" id="switchCode">
							</div>
						</div>
						<div class="form-group text-center m-b-0">
							<div class="col-xs-12">
								<button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="button" id="btnLogin">Ingresar</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<footer class="footer text-center">
			© <?= date('Y') ?> <small>Hospital Veterinario</small> Peek
		</footer>
		
		<script src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/toast/toastr.min.js"></script>
		<script>
			$(function(){
				$(".preloader").fadeOut();
				toastr.options = {									
					"positionClass": "toast-top-right",
					"timeOut": "4000",
				}
                
				$('#switchCode').focus();
				$('#switchCode').keyup(function(e) { e.preventDefault(); if(e.keyCode == 13) $('#btnLogin').trigger('click'); });
				
                $attemps = 0;
                $('#btnLogin').click(function(e){
					e.preventDefault();
                    $('#switchCode').removeClass('is-invalid');
                    code = $.trim($('#switchCode').val());
                    if(code == ''){
                        $('#switchCode').addClass('is-invalid').focus();
                    }else{
                        blockPage();
                        $.post(`<?= URL_ROOT ?>/usuario/login/`, {code: code},
                            function (resp) {
                                if(resp.response){
                                    setTimeout(() => {
                                        window.location = decodeURIComponent('<?= isset($_SESSION['next']) ? $_SESSION['next'] : URL_ROOT.'/agenda' ?>');
                                    }, 1000);
                                }else{
                                    toastr['error']('Switch Code Incorrecto');
                                }
                                $.unblockUI();
                            },
                            "json"
                        );
                    }
                });

				function blockPage(){
					$.blockUI({ 
						message: '<i class="icon-spinner4 spinner"></i>',
						overlayCSS: {
							backgroundColor: '#1b2024',
							opacity: 0.8,
							zIndex: 1200,
							cursor: 'wait'
						},
						css: {
							border: 0,
							color: '#fff',
							padding: 0,
							zIndex: 1201,
							backgroundColor: 'transparent'
						}
					});
				}
				
			});
		</script>
	</body>

</html>